### YamlMime:Sample
sample:
- name: App package information sample
  description: This sample shows you how to get package info by using the Windows Runtime packaging API (Windows.ApplicationModel.Package and Windows.ApplicationModel.PackageId).
  generateZip: false
  author: oldnewthing
  languages:
  - csharp
  - cpp
  - js
  technologies:
  - windows